import openai


# Step 1: Configure the API client
openai.api_key = "sk-96e2096fd7d54063844bdfbdd022c1ff"
openai.base_url = "https://api.deepseek.com"  # Replace with the actual endpoint if needed


# Step 2: Define the agent function
def query_agent(prompt, model="deepseek-model-name", max_tokens=1000):
    """
    Sends a prompt to the Deepseek model and retrieves the response.
    
    Args:
        prompt (str): The input text or question for the model.
        model (str): The name of the model to use (e.g., "deepseek-model-name").
        max_tokens (int): The maximum number of tokens in the response.
    
    Returns:
        str: The response generated by the model.
    """
    try:
        # Use the new OpenAI client (introduced in v1.0.0)
        client = openai.OpenAI(api_key=openai.api_key, base_url=openai.base_url)
        
        # Send the request to the model
        response = client.chat.completions.create(
            model=model,             # Specify the model name
            messages=[{"role": "user", "content": prompt}],  # Input prompt
            max_tokens=max_tokens,   # Limit the response length
            temperature=0.7,         # Control randomness (0.0 to 1.0)
            n=1                      # Number of responses to generate
        )
        
        # Extract the response text
        return response.choices[0].message.content.strip()
    
    except Exception as e:
        print(f"An error occurred: {e}")
        return None


# Step 3: Define a conversation-based agent
class ConversationAgent:
    def __init__(self, model="deepseek-model-name"):
        self.model = model
        self.history = []

    def add_message(self, role, content):
        """Add a message to the conversation history."""
        self.history.append({"role": role, "content": content})

    def query(self, user_input, max_tokens=1000):
        """Send a query to the model with conversation history."""
        self.add_message("user", user_input)
        
        # Query the model
        response = query_agent(
            prompt="\n".join([f"{msg['role']}: {msg['content']}" for msg in self.history]),
            model=self.model,
            max_tokens=max_tokens
        )
        
        if response:
            self.add_message("assistant", response)
            return response
        return None

# Step 4: Interact with the agent
if __name__ == "__main__":
    # Example usage of the simple query_agent function
    user_prompt = "Explain the concept of artificial intelligence in simple terms."
    # deepseek-chat     deepseek-reasoner
    response = query_agent(user_prompt, model="deepseek-reasoner")
    if response:
        print("Agent Response:")
        print(len(response))
        print(response)

    # Example usage of the ConversationAgent class
    print('------------------------------------------------')
    agent = ConversationAgent(model="deepseek-reasoner")
    response = agent.query("What is machine learning?")
    print(response)